### ISSUE TITLE
[fr] drag and drop alarms/timers

### ISSUE THREAD

**Issue by useless642** [FossifyOrg/Clock#24] opened 2024-02-21 17:12 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

currently, there's no way to manually change the order of alarms and timers, there's no drag and drop option.

### Why do you want this feature?

it's important to have the option to manually change the order of those things because the only way to "change the order" right now is by deleting them and making them again in the order that we want...

### Additional information

I've already talked about this [feature request](https://github.com/SimpleMobileTools/Simple-Clock/issues/451) in the original SimpleMobileTools repository.

**Comment by Aga-C** [comment] 2024-02-21 17:25
It's a duplicate of https://github.com/FossifyOrg/Clock/issues/8.

**Closed by Aga-C** 2024-02-21 17:25 UTC
Labels: feature request, needs triage
