### ISSUE TITLE
Alarm not synchronised with phone time

### ISSUE THREAD

**Issue by HappyClem** [FossifyOrg/Clock#98] opened 2024-10-28 08:10 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 9 MIUI 11.0.3.0

### Affected device model

Xiaomi 9T

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Set an alarm (e.g. 10am)
2. Disable "Automatic hour/date" on your phone
3. Change your phone hour/date (e.g. -1h from actual time)
4. Wait for the alarm

### Expected behavior

Alarm should follow device hour/date so any alarms goes at the local time in case of changes of time.

### Actual behavior

Alarms goes off at the time before the time change.
E.G. If I set an alarm at 10pm when it's 9pm and I change my phone hour/date to 8pm, the alarm will go at 9pm (-1h)

### Additional information

Hello,

I discovered this because this weekend we switched times because of daylights savings.

My phone has hour/date automatic enable, but my alarm went off  1 hour early. A friend using the app had the same issue on a different model.

I hope it is explained correctly. Thanks for the app !

**Comment by rhysperry111** [comment] 2024-10-28 08:32
Think I experienced this as well - this was the first workday since the clocks went back.

Even though the system time had correctly synced, the alarm went off an hour early. Simply turning the alarm off and on again reset it to an hour later so I could get some more sleep :)

**Comment by Aga-C** [comment] 2024-10-28 08:32
It's a duplicate of https://github.com/FossifyOrg/Clock/issues/61.

**Closed by Aga-C** 2024-10-28 08:32 UTC
Labels: bug, needs triage
