### ISSUE TITLE
alarm wont load on device reboot 

### ISSUE THREAD

**Issue by truong0235** [FossifyOrg/Clock#68] opened 2024-04-26 03:50 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Clock/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

### Affected app version

newest (1.0.0)

### Affected Android/Custom ROM version

Miui global 13.0.16.0, android 11

### Affected device model

Poco c40

### How did you install the app?

Third-party website

### Steps to reproduce the bug

1. allow app to run in backgroud, turn on autostart, lock app to avoid being clear in recent
2. set an arlam 
3. reboot device without unlock the screen

### Expected behavior

alarm should work as expected

### Actual behavior

nothing happened 

### Additional information

native clock app (https://www.apkmirror.com/apk/xiaomi-inc/miui-clock/miui-clock-15-26-0-release/) does work normally afer reboot
seems like Chinese rom issue when they restric background apps

**Comment by Aga-C** [comment] 2024-04-26 06:01
I can reproduce it while having a password-locked screen - alarm doesn't work like you described it. However, on the second phone without password lock it's working fine, so the bug is connected to that.

**Comment by naveensingh** [comment] 2024-04-26 06:03
Duplicate of https://github.com/FossifyOrg/Clock/issues/17

**Closed** 2024-04-26 06:06 UTC
Labels: bug
