### ISSUE TITLE
Change Timer duration setting to use keypad instead of scrolling selectors

### ISSUE THREAD

**Issue by quickishfm** [FossifyOrg/Clock#97] opened 2024-10-06 22:01 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Adding a timer and clicking the duration opens a scrolling duration selector for hours, minutes and seconds.
<img alt="Screenshot_20241006-104552_Clock" src="https://github.com/user-attachments/assets/e74beacf-9e81-4673-adcc-4a4ede3cc3a5" width=184 />
 This can get tiring when needing to scroll to the end, and a keypad here would allow for quicker entry.

### Why do you want this feature?

Scrolling the minutes and seconds takes too long and would be much quicker to type the number

**Comment by Aga-C** [comment] 2024-10-07 05:34
It's a duplicate of https://github.com/FossifyOrg/Clock/issues/63.

**Closed by Aga-C** 2024-10-07 05:34 UTC
Labels: feature request, needs triage

**Comment by quickishfm** [comment] 2024-10-07 05:40
Ah, sorry, that didn't come up in my search (I searched for keypad in the issues but it was named differently).
