### ISSUE TITLE
Power off alarm

### ISSUE THREAD

**Issue by shihaamabr** [FossifyOrg/Clock#95] opened 2024-09-28 02:50 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Clock/issues) or [closed](https://github.com/FossifyOrg/Clock/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Clock/discussions) or [closed](https://github.com/FossifyOrg/Clock/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Implement Power Off Alarm functionality in the app. This feature allows the app to set and clear alarms that can wake up the device from a powered-off state. Many Android ROMs support this feature (I believe they're forked off AOSP clock). 
It ensurs alarms work even when the device is completely powered off.

### Why do you want this feature?

Users intentionally power off their devices to save battery or avoid disturbances will still have working alarm, I have my phone set to turn off when battery reaches 5% just so alarms will still work. 

### Additional information

AOSP Clock supports this feature, https://github.com/qw123wh/Aospdeskclock is a fork of AOSP clock (this app also support it)

![image](https://github.com/user-attachments/assets/9e21f23a-88ef-4349-8843-3ee64c9908e6)
![image](https://github.com/user-attachments/assets/e0c88668-b54e-4399-9e7c-f16264a7396d)

**Comment by shihaamabr** [comment] 2024-09-28 02:53
Google, Samsung, Oneplus, Xioami dont support this feature though... :/

**Comment by Aga-C** [comment] 2024-09-28 05:29
It's a duplicate of https://github.com/FossifyOrg/Clock/issues/92.

**Closed by Aga-C** 2024-09-28 05:29 UTC
Labels: feature request, needs triage
